import type { Metadata } from "next";
import Footer from "./components/footer";
import Navbar from "./components/navbar";

import "./globals.css";
import { SanityLive } from "@/sanity/live";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body className="flex flex-col min-h-screen">
        <Navbar />
        <main className="flex-grow">{children}</main>
        <Footer></Footer>
        <SanityLive />
      </body>
    </html>
  );
}
